<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DistributionSystem.Data</RootNamespace>
    <AssemblyName>DistributionSystem.Data</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
