<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>DistributionSystem.Business</RootNamespace>
    <AssemblyName>DistributionSystem.Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DistributionSystem.Data\DistributionSystem.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
  </ItemGroup>

</Project>
